version: '3.8'

services:
  ollama-api:
    build: .
    container_name: ollama-api-service
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=${SECRET_KEY:-NKLdJTql1oGCsTOGqdpJGVQCkt6FntM5D5ffiODjqRc}
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL:-http://host.docker.internal:11434}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES:-60}
    restart: unless-stopped
    networks:
      - ollama-network

networks:
  ollama-network:
    driver: bridge
